// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoVIqcQk3RUljl9qTaJH2hqZt0GxwYEM0',
    appId: '1:182476836410:web:4e1b9f78e9cf3f1bdf2f03',
    messagingSenderId: '182476836410',
    projectId: 'modastore-bfc8a',
    authDomain: 'modastore-bfc8a.firebaseapp.com',
    databaseURL: 'https://modastore-bfc8a-default-rtdb.firebaseio.com',
    storageBucket: 'modastore-bfc8a.appspot.com',
    measurementId: 'G-N8BW9KB4TW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHG9j4Uz9nq3Ys8U5jrtyM-Pwem8m6Nf0',
    appId: '1:182476836410:android:a87dab87e21e71afdf2f03',
    messagingSenderId: '182476836410',
    projectId: 'modastore-bfc8a',
    databaseURL: 'https://modastore-bfc8a-default-rtdb.firebaseio.com',
    storageBucket: 'modastore-bfc8a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6ESMnWUTuvZjaGSh0Js80ugcTnvgSIt4',
    appId: '1:182476836410:ios:35b69eeed3aaa9eddf2f03',
    messagingSenderId: '182476836410',
    projectId: 'modastore-bfc8a',
    databaseURL: 'https://modastore-bfc8a-default-rtdb.firebaseio.com',
    storageBucket: 'modastore-bfc8a.appspot.com',
    androidClientId: '182476836410-92fq6fcd9jk7caj5vhvr5dpflolep5al.apps.googleusercontent.com',
    iosClientId: '182476836410-4uusamh06ft7aae6po6l5j9comvf4e3b.apps.googleusercontent.com',
    iosBundleId: 'com.youce.mStore',
  );
}
